# Generated by Django 2.2.5 on 2020-06-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relpy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
